name: Test:e2e(all)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
env:
  BUCKET_ENV_BACKBLAZE: ${{ secrets.BUCKET_ENV_BACKBLAZE }}
  BUCKET_ENV_MINIO: ${{ secrets.BUCKET_ENV_MINIO }}
  BUCKET_ENV_CLOUDFLARE: ${{ secrets.BUCKET_ENV_CLOUDFLARE }}
  BUCKET_ENV_DIGITALOCEAN: ${{ secrets.BUCKET_ENV_DIGITALOCEAN }}
  BUCKET_ENV_GARAGE: ${{ secrets.BUCKET_ENV_GARAGE }}
  BUCKET_ENV_CEPH: ${{ secrets.BUCKET_ENV_CEPH }}
  BUCKET_ENV_SCALEWAY: ${{ secrets.BUCKET_ENV_SCALEWAY }}
  BUCKET_ENV_HETZNER: ${{ secrets.BUCKET_ENV_HETZNER }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: Check Docker version
        run: docker --version && docker compose version

      - uses: https://data.forgejo.org/actions/setup-node@v4
        with:
          node-version: 20

      - uses: https://github.com/oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run e2e tests (Node)
        uses: https://github.com/nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2 pin
        with:
          max_attempts: 3
          retry_on: any
          timeout_minutes: 10
          retry_wait_seconds: 30
          command: npm run test:e2e
        env:
          BUCKET_ENV_BACKBLAZE: ${{ secrets.BUCKET_ENV_BACKBLAZE }}
          BUCKET_ENV_CLOUDFLARE: ${{ secrets.BUCKET_ENV_CLOUDFLARE }}
          BUCKET_ENV_DIGITALOCEAN: ${{ secrets.BUCKET_ENV_DIGITALOCEAN }}
          BUCKET_ENV_GARAGE: ${{ secrets.BUCKET_ENV_GARAGE }}
          BUCKET_ENV_MINIO: ${{ secrets.BUCKET_ENV_MINIO }}
          BUCKET_ENV_CEPH: ${{ secrets.BUCKET_ENV_CEPH }}
          BUCKET_ENV_SCALEWAY: ${{ secrets.BUCKET_ENV_SCALEWAY }}
          BUCKET_ENV_HETZNER: ${{ secrets.BUCKET_ENV_HETZNER }}

      - name: Run e2e tests (Bun)
        uses: https://github.com/nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2 pin
        with:
          max_attempts: 3
          retry_on: any
          timeout_minutes: 10
          retry_wait_seconds: 30
          command: npm run test:e2e:bun
        env:
          BUCKET_ENV_BACKBLAZE: ${{ secrets.BUCKET_ENV_BACKBLAZE }}
          BUCKET_ENV_CLOUDFLARE: ${{ secrets.BUCKET_ENV_CLOUDFLARE }}
          BUCKET_ENV_DIGITALOCEAN: ${{ secrets.BUCKET_ENV_DIGITALOCEAN }}
          BUCKET_ENV_GARAGE: ${{ secrets.BUCKET_ENV_GARAGE }}
          BUCKET_ENV_MINIO: ${{ secrets.BUCKET_ENV_MINIO }}
          BUCKET_ENV_CEPH: ${{ secrets.BUCKET_ENV_CEPH }}
          BUCKET_ENV_SCALEWAY: ${{ secrets.BUCKET_ENV_SCALEWAY }}
          BUCKET_ENV_HETZNER: ${{ secrets.BUCKET_ENV_HETZNER }}
